{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
source:
  git_url: ../

package:
  name: wheeler.pygtkhelpers
  version: {{ GIT_VERSION }}

build:
    script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python 2.7*
    - cairo-helpers
    #: ..versionadded:: X.X.X
    - debounce
    - flatland-fork
    - jupyter-helpers >=0.10
    - jsonschema
    - pycairo-gtk2
    - redirect-io
    - si-prefix >=0.4
    - svg-model >=0.5.post18
    - trollius

  run:
    - blinker
    - cairo-helpers
    #: ..versionadded:: X.X.X
    - debounce
    - flatland-fork
    - jupyter-helpers >=0.10
    - jsonschema
    - pycairo-gtk2
    - redirect-io
    - si-prefix >=0.4
    - svg-model >=0.5.post18
    - trollius
